development:
  adapter: mysql2
  encoding: utf8
  database: metal_collection_dev
  pool: 5
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql2
  encoding: utf8
  database: metal_collection_test
  pool: 5
  username: root
  password:
  host: localhost
